 printf("Inizio Introduzione Episodio 1");	
  printf("Ragazzo:Hai sentito di Misaki?\n");
  sleep (5);
  printf("Ragazzo:Era al nono anno, nella sezione 3\n");
  sleep (5);
  printf("Ragazza:C'era qualcuno che si chiamava Misaki nella sezione 3?\n");
  sleep (5);
  printf("Ragazzo:E' successo 26 anni fa.\n");
  sleep (5);
  printf("Ragazzo:Fino al settimo grado, era una ragazza popolare\n");
  sleep (5);
  printf("Ragazzo:Era intelligente, carina e aveva una grande personalita'\n");
  sleep (5);
  printf("Ragazzo:Sia i professori che gli studenti l'adoravano.\n");
  sleep (5);
  printf("Ragazza:C'e' sempre qualcuno così in ogni anno.\n");
  sleep (5);
  printf("Ragazzo:Pero' poco dopo l'inizio del 9 anno...\n");
  sleep (5);
  printf("Ragazzo:Misaki mori'.\n");
  sleep (5);
  printf("Ragazza:Come e' successo?\n");
  sleep (5);
  printf("Ragazzo:Ho sentito che si e' trattato di un incidente\n");
  sleep (5);
  printf("Ragazzo:Ovviamente tutti quanti sono rimasti shokati\n");
  sleep (5);
  printf("Ragazzo:Fino a quando una persona ha detto.\n");
  sleep (5);
  printf("Ragazza:Detto cosa?\n");
  sleep (5);
  printf("Ragazzo:Ha puntato al banco di Misaki e ha detto:\n");
  sleep (5);
  printf("Ragazzo:'Misaki e' li'. 'Non e' morta.'\n");
  sleep (5);
  printf("Ragazza:Ed era cosi'...?\n");
  sleep (5);
  printf("Ragazzo:Beh, era solo una finta.\n");
  sleep (5);
  printf("Ragazzo:Ma da quel momento, la sezione 3 ha continuato a fingere che Misaki fosse ancora in vita.\n");
  sleep (5);
  printf("Ragazza:E' inquietante.\n");
  sleep (5);
  printf("Ragazzo:Hanno continuato a fingere fino alla graduazione.\n");
  sleep (5);
  printf("Ragazzo:Il preside ha perfino organizzato la cerimonia di graduazione facendo mettere la sedia di Misaki.\n");
  sleep (5);
  printf("Ragazza:E' una buona cosa no?\n");
  sleep (5);
  printf("Ragazzo:Se fosse stata la fine, si.\n");
  sleep (5);
  printf("Ragazza:C'e' dell'altro?\n");
  sleep (5);
  printf("Ragazzo:Il resto della storia e'...\n");
  sleep (10);